### ISSUE TITLE
Dangerous Pre-Arm  state

### ISSUE THREAD

**Issue by shanggl** [BossHobby/QUICKSILVER#108]
With the  Pre-Arm switch  and arm switch on but  the throttle is high , the drone is armed but the  the motor is not  running , it's in a Dangerous State ! ,if the throttle gets down by mis-operation or accident , the motor starts to spin !  

so , the pre-arm is not "pre-arm" , hope the drone get armed only  with the right  sequence : pre-arm on  & throttle at low  then arm aux channel no .  it will  prevent a lot of accident . 

or arm with  the same arm aux channle switch on  "Twice "  when the throttle is at low

**Comment by bkleiner** [comment]
the rational here is that if your drone becomes disarmed because of a failsafe, it gives you the chance to regain control if the radio link comes back.
with your proposal you would have to disarm, cut throttle, apply pre-arm, arm and raise throttle while your quad is falling from the sky.

**Comment by bkleiner** [comment]
throttle low was added to the pre-arm conditions in e773600b4f09c1496bf0ee1aad8a317c78e9f2e1 
additionally a "failsafe lockout" was implemented that allows one to re-arm within a certain time frame after a failsafe without needing to pass the throttle check.
