### ISSUE TITLE
Correct target for FC

### ISSUE THREAD

**Issue by Chekagos** [BossHobby/QUICKSILVER#111]
Please help me with my FC target choice 
My FC - Mamba F722 mini MK2  
is it the same as the target into qicksilver app - Mamba F722_i2C ?
Thanks for your help 
Id love to try this configurator

**Comment by bkleiner** [comment]
yes, we try to match the betaflight targets wherever it makes sense.
So MAMBAF722_I2C is the correct target.
General questions like this are best asked on [discord](https://discord.gg/8StVhvB6Tm)
