### ISSUE TITLE
blackbox log download fail

### ISSUE THREAD

**Issue by amitleibov** [BossHobby/QUICKSILVER#112]
I record blackbox logs, they appear to be on the FC, however downloading them ends with an error message "blackbox download failed"
what could be the reason ?
FC JHEF405PRO target  quicksilver ver 0.10.2
![Screenshot 2024-01-14 151422](https://github.com/BossHobby/QUICKSILVER/assets/7338697/173c4211-6d03-4d97-adef-7332d1770743)

**Comment by amitleibov** [comment]
![Screenshot 2024-01-14 151921](https://github.com/BossHobby/QUICKSILVER/assets/7338697/3380ac95-718d-42ae-a0dd-f9fe41b573f8)

**Comment by amitleibov** [comment]
![Screenshot 2024-01-14 153121](https://github.com/BossHobby/QUICKSILVER/assets/7338697/634a3c0e-c8ad-4241-a95c-d4d24f528ee8)

**Comment by amitleibov** [comment]
I 
![Screenshot 2024-01-14 182018](https://github.com/BossHobby/QUICKSILVER/assets/7338697/29bc370f-d13b-42ef-83ff-86f73cbbaadb)
can confirm that on another drone it works fine .... I'd still want to know if there is a bug that can be fixed, as I want blackbox to analyze my drone build.. Thanks.

**Comment by bkleiner** [comment]
There are a number of reasons why the download failed, however most common seems to be that some flight-controller/computer combinations do not fully deliver the data to the browser. 

Could you:
a) try to download the existing log a couple more times, aforementioned problem does not manifest consistently.
b) try recording another (shorter) log and try downloading then.

**Comment by amitleibov** [comment]
thanks for the fast response. deleted the files and tried another flight and this time downloaded as expected.
