### ISSUE TITLE
Corrupted target config for Speedybee F405 V4

### ISSUE THREAD

**Issue by matiss** [BossHobby/QUICKSILVER#117]
Flashed fresh Speedybee F405 V4 FC with Quicksilver firmware version v0.10.5 and v0.11.0-RC and target config file was corrupted. It was missing config for motor pins and motors weren't working at all.

I tried to re-apply target file `spbe-speedybeef405v4.yaml` from the repo to no avail. But other target config files worked, although they were for different boards.

I managed to make it work by removing these following lines:
```
sdcard_detect:
  invert: true
  pin: None
```

**Comment by chaotixtech** [comment]
Does that fc actually have an sdcard? I don't have samples of most fc and generally add as requested asking the user to test.

**Comment by chaotixtech** [comment]
Removed that section from the target as it's not needed. Should be issue closed, thanks.

**Comment by bkleiner** [comment]
thanks, this revealed a bug in the target parser. it used to be case sensitive, now rectified. https://github.com/BossHobby/QUICKSILVER/commit/7bf0805da8b98cd80e9d952a768cf70ef1e66e9f
