### ISSUE TITLE
[help] platformIO build error

### ISSUE THREAD

**Issue by vangao-gg** [BossHobby/QUICKSILVER#118]
hi everyone,
QS is a very good project, and I want to try compiling the latest code in Windows, but encountered the following error message during compilation:
<img width="418" alt="a02e2adc5329c2a7beede72f13e005c" src="https://github.com/user-attachments/assets/06a6ad66-3831-4b23-8eae-9fb1946fd3d9">

1. The commit version is: bump version; c5d58c21cb156c4caa15ab2a72b12445915ede15
2. platformIO core 6.1.16 and home 3.4.4
3. The list results are as follows:
<img width="387" alt="bca69a064507a550a1bc5f275df14b7" src="https://github.com/user-attachments/assets/03de9481-051f-43ce-97bf-bff9543bbbc5">

4. I switched the branch of the repository to 0.10.0, and the compilation is normal

**Comment by bkleiner** [comment]
interesting. i dont think the commit you point out is at fault - that file indicates the version to the configurator and is of no relevance for pio. 
can you try deleting the `.platformio` folder in your windows user folder? looks to me maybe something got corrupted during download.

**Comment by vangao-gg** [comment]
Thank you, bkleiner. Following your instructions, I deleted the. platformio fold and reconfigured it. The build is now normal. Thank you again and have a nice day;
