### ISSUE TITLE
feature-blackbox

### ISSUE THREAD

**Issue by NotFastEnuf** [BossHobby/QUICKSILVER#29]
...placeholder

**Comment by lmnn** [comment]
My vote for bb logging feature...

**Comment by bkleiner** [comment]
_slowly_ getting there on firmware side recording.....just a ton of edge-cases to handle.
wonder if i my current system is just inherently brittle. 

made some good progress on getting the usb-transfer faster and more reliable.
https://github.com/BossHobby/QUICKSILVER/commit/54374681db7c07bf1698616fb3db652b76104dd6
proper zlp handling made a huge difference

For analysis, i have started my own interface. Aims to strike a balance between the BF BB explorer and the PIDToolbox. very early days still
https://github.com/BossHobby/Blackbox-Analyzer

**Comment by sixtyfive** [comment]
Any updates? :)

**Comment by bkleiner** [comment]
There have been some improvements like adding presets for different amounts of data logged in #96
and some general code cleanups 295cae5737a134b1c46d0e62771accb99ba46518

I still don't love UX and reliability of all of it, but closing this issue as the original premise has long been achieved.

**Comment by sixtyfive** [comment]
Apologies for the necromancing then ... but since I can't find anything clicking around in QSC and the docs are also quiet when searching them for `blackbox`: where does one download/access the recordings?

**Comment by bkleiner** [comment]
a tab in the configurator will show up _if your fc has a recording device_.
if you are not seeing one, your fc most likely simply doesnt have one.

**Comment by sixtyfive** [comment]
Hmm, I see. Would it not be better, UX-wise, to have the tab be there all the time, but show "no recording device" found?
