### ISSUE TITLE
Feature DSHOT motor beep

### ISSUE THREAD

**Issue by Noramas** [BossHobby/QUICKSILVER#35]
Hi, please regard possibility to implement DSHOT motor beep.

This can be convenient for pilots who use smaller and bigger quads without dedicated beeper. DSHOT beep would be essential feature to be able to search model in the grass.

**Comment by bkleiner** [comment]
basic version of this feature was merged in #38 motor beep is now available by default and can be activated with the `AUX_BUZZER_ENABLE` aux feature
