### ISSUE TITLE
Request: flight time counter in OSD

### ISSUE THREAD

**Issue by Noramas** [BossHobby/QUICKSILVER#36]
Please consider to implement flight time counter in OSD. Counter should be running only when drone is armed.
It's essential feature for drone pilots to be able to monitor flight time instead of total drone power up time

**Comment by Noramas** [comment]
This was already discussed 
https://github.com/NotFastEnuf/NFE_QUICKSILVER/issues/4

**Comment by bkleiner** [comment]
im very much in favor of this feature, i just really haven't gotten around to look at it.
PRs welcome

**Comment by bkleiner** [comment]
basic arm timer was merged in #45
