### ISSUE TITLE
disallow buzzer racket while connected to USB 

### ISSUE THREAD

**Issue by Noramas** [BossHobby/QUICKSILVER#42]
Very annoying feature. Buzzer is beeping every time when connected to USB during setup process. 
https://github.com/NotFastEnuf/NFE_QUICKSILVER/commit/5a146622d90fd39be68b47bc4faae29f51a2e4b1
Please consider to merge into new project

**Comment by bkleiner** [comment]
huh i guess i missed that one when i synced the repos, 
no lives in https://github.com/BossHobby/QUICKSILVER/commit/8def30b5781195a90415ab07cf7e1a43bd1116a4
