### ISSUE TITLE
Request: Add throttle settings to configurator

### ISSUE THREAD

**Issue by DyoGTS** [BossHobby/QUICKSILVER#44]
Request to add throttle settings to configurator. Allowing pilots to change throttle settings per quad will allow pilots to use a single model on the radio.

**Comment by bkleiner** [comment]
a motor limit landed in https://github.com/BossHobby/QUICKSILVER/commit/5fb276ab9f4a07b2a95cd354e7e768e453db2e12 and following

**Comment by bkleiner** [comment]
throttle mid and expo landed in 0.8.5
