### ISSUE TITLE
Request: add pre-arm channel

### ISSUE THREAD

**Issue by bkleiner** [BossHobby/QUICKSILVER#47]

**Comment by vileperson** [comment]
Preferably to mimic the *Flight firmwares, where "pre-arm" can be set to a momentary switch so that it only has to be "high" at the moment of arming, and doesn't have to remain high to stay armed.

**Comment by bkleiner** [comment]
landed with https://github.com/BossHobby/QUICKSILVER/commit/f0c48db20b84b4ff104094f5bcbd9c7f94b53324
