### ISSUE TITLE
VTX appears to be stuck in PIT mode

### ISSUE THREAD

**Issue by Stampede10343** [BossHobby/QUICKSILVER#63]
I just tried flashing 0.9.0 onto a HM Diamond F4 FRSky board using the  CrazyBee FR Brushless target and it auto-detected Smart Audio and appears to set the right band and channel, but the power is extremely low, any further away than a few feet and the video drops out.

**Comment by Stampede10343** [comment]
Nevermind.. OpenVTX has 0mw/PIT/25mw, so levels 1 and 2 were basically PIT mode.

**Comment by bkleiner** [comment]
right,  #61 will bring some improvements to this.
