### ISSUE TITLE
Not connecting to bootloader after flashing. Also, won't connect to configurator after flashing

### ISSUE THREAD

**Issue by FlyinRyanFPV** [BossHobby/QUICKSILVER#82]
I have a CrazyBee F4 DX Pro V2.0. FC was working fine with BF but when I flashed Quicksilver to it it won't connect to the configurator now. I am now unable to re-flash Betaflight back on it as it will not go into the bootloader/DFU now after flashing Quicksilver. I tried the Zadig program to no avail with it not going into the bootloader. When I hold the Bootloader button and power it, it won't connect to the computer or anything.
Please help!

Thanks,
Ryan

**Comment by bkleiner** [comment]
I am sorry, but this not a support forum. DFU mode operates independently from firmware. Check our [docs](https://docs.bosshobby.com/Troubleshooting/) or hop on our [discord](https://discord.gg/8StVhvB6Tm).
