### ISSUE TITLE
correct set point scaling in deg/s

### ISSUE THREAD

**Issue by bw1129** [BossHobby/QUICKSILVER#97]
Hi guys. I am trying to get PIDtoolbox to accurately read QS logfiles. The main issue I am seeing is that set point as extracted from the logfiles (BF converted log) is not in deg/s and doesnt seem to take into account rates, though I cant be sure, so I dont think it's a simple linear scaling. I tried dividing setpoint/10 and it is closer but certainly not correct. Be great if this was corrected then I can implement PTB tuning protocol for those interested. (plot below shows current set point (red) vs gyro (black), with SP/10, which is clearly not working; motor sigs also not scaled correctly there but that will be a simple linear re-scaling that I can do on my end) 
![image](https://user-images.githubusercontent.com/17284912/236519055-b581d00f-6ced-4719-ac54-af2b36eec639.png)

**Comment by bkleiner** [comment]
fix in https://github.com/BossHobby/Configurator/commit/df148e7f4c13cb5b5d98d566de1446c2af91c9e9
